[build-system]
requires = ["setuptools>=70.1", "wheel", "ninja", "packaging"]
build-backend = "setuptools.build_meta"

[project]
name = "causal-conv1d"
version = "1.6.1"
description = "Causal depthwise conv1d in CUDA, with a PyTorch interface"
readme = "README.md"
requires-python = ">=3.11"
license-files = ["LICENSE"]
dependencies = [
    "torch",
]

[tool.uv.extra-build-dependencies]
causal-conv1d = [{ requirement = "torch", match-runtime = true }]